name: Clang-Tidy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install clang-tidy
      run: ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"

    - name: configure
      run: cmake -Hstandalone -Bbuild -DUSE_STATIC_ANALYZER='clang-tidy'

    - name: build & check
      run: cmake --build build -j4